ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "payroll_paid_amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "payroll_received_amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
